In [1]:
print("hello")

hello

In [1]:
import os
from dotenv import load_dotenv, find_dotenv
from datasets import load_dataset
from pathlib import Path

load_dotenv(find_dotenv())

c:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

True

In [2]:
import pandas as pd

In [6]:
df.head()

,sn,time,timeStr,dataTimestamp,inverterId,inverterSn,currentState,warningInfoData,alarmState,pac,...,plimitSet,pfactorLimitSet,preactiveLimitSet,psumCal,totalAndSmartLoadPower,pepmSet,pepm,sixteen,energyControl,pumpControl
0,10050A021914000,2023-06-01 16:33:36,01/06/2023 16:33:36 (UTC+05:30),1685617416000,1308675217948139792,10050A021914000,正常,0,1,230.0,...,0.0,0.0,0.0,230.0,0.0,0.0,0.0,NaN,NaN,NaN
1,10050A021914000,2023-06-01 16:39:11,01/06/2023 16:39:11 (UTC+05:30),1685617751000,1308675217948139792,10050A021914000,正常,0,1,990.0,...,0.0,0.0,0.0,990.0,0.0,0.0,0.0,NaN,NaN,NaN
2,10050A021914000,2023-06-01 16:44:37,01/06/2023 16:44:37 (UTC+05:30),1685618077000,1308675217948139792,10050A021914000,正常,0,1,950.0,...,0.0,0.0,0.0,950.0,0.0,0.0,0.0,NaN,NaN,NaN
3,10050A021914000,2023-06-01 16:55:05,01/06/2023 16:55:05 (UTC+05:30),1685618705000,1308675217948139792,10050A021914000,正常,0,1,850.0,...,0.0,0.0,0.0,850.0,0.0,0.0,0.0,NaN,NaN,NaN
4,10050A021914000,2023-06-01 17:00:20,01/06/2023 17:00:20 (UTC+05:30),1685619020000,1308675217948139792,10050A021914000,正常,0,1,790.0,...,0.0,0.0,0.0,790.0,0.0,0.0,0.0,NaN,NaN,NaN

### check if the file name and files are maching

In [ ]:
# old

# infolist=[
#   {"file": "CRN 10049 Meepe,Habaraduwa_1.csv", "town": "Habaraduwa", "district": "Galle", "pv_capacity_kwp": 6.48},
#   {"file": "CRN 11183 Ambalangoda_1.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 15},
#   {"file": "CRN 11630 Molligoda,Wadduwa (Convert)_1.csv", "town": "Wadduwa", "district": "Kalutara", "pv_capacity_kwp": 5},
#   {"file": "CRN 12157.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 5.2},
#   {"file": "CRN 12200 ( Hybrid )Milidduwa, Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 5},
#   {"file": "CRN 14857 Karapitiya Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 6},
#   {"file": "CRN 18434 Polwatta Road, Ambalangoda_1.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 5},
#   {"file": "CRN 18649 Thottawatta Road, Ahungalla_1.csv", "town": "Ahungalla", "district": "Galle", "pv_capacity_kwp": 7.25},
#   {"file": "CRN 26198 ( Hybrid ) Weheragoda,Ahangama.csv", "town": "Ahangama", "district": "Galle", "pv_capacity_kwp": 5.5},
#   {"file": "CRN 28970 Handigoda Hikkaduwa_1.csv", "town": "Hikkaduwa", "district": "Galle", "pv_capacity_kwp": 5},
#   {"file": "CRN 31575 Hirimbura Road, Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 3.2},
#   {"file": "CRN 32558 Pitiwella,Boossa_1.csv", "town": "Boossa", "district": "Galle", "pv_capacity_kwp": 5},
#   {"file": "CRN 33061_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 8},
#   {"file": "CRN 34350 Walahanduwa,Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 3},
#   {"file": "CRN 37399 Karaputiya.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 3.9},
#   {"file": "CRN 38794 Ambalangoda.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 3.1},
#   {"file": "CRN 39828 Anagarika dharmapala mawatha Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 6},
#   {"file": "CRN 39939 Thawaluwila, Ambalantota (Convert)_1.csv", "town": "Ambalantota", "district": "Hambantota", "pv_capacity_kwp": 5},
#   {"file": "CRN 40400 Labuduwa, Gall_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 5},
#   {"file": "CRN 40774 Payagala Kaluthara_1.csv", "town": "Payagala", "district": "Kalutara", "pv_capacity_kwp": 20},
#   {"file": "CRN 41208 mathugama pradeshiya saba_1.csv", "town": "Matugama", "district": "Kalutara", "pv_capacity_kwp": 6},
#   {"file": "CRN 49244 Bope Cross Rd,Galle._1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 4.95},
#   {"file": "CRN 52354_1.csv", "town": "Ahangama", "district": "Galle", "pv_capacity_kwp": 17},
#   {"file": "CRN 52674 Porabha Ambalangoda_1.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 6},
#   {"file": "CRN 52890 Molligoda Wadduwa_1.csv", "town": "Wadduwa", "district": "Kalutara", "pv_capacity_kwp": 5},
#   {"file": "CRN 52919 Wathugedara Ambalangoda_1.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 8},
#   {"file": "CRN 53084, K K M R I W D K Purijjala, Sella Katharagama_1.csv", "town": "Sella Kataragama", "district": "Monaragala", "pv_capacity_kwp": 27.5},
#   {"file": "CRN 53200 Meegahawela road Beliattha_1.csv", "town": "Beliatta", "district": "Hambantota", "pv_capacity_kwp": 15.4},
#   {"file": "CRN 53204 Mailagama Katharagama_1.csv", "town": "Sella Kataragama", "district": "Monaragala", "pv_capacity_kwp": 16.52},
#   {"file": "CRN 53444 Thissapura Uhana ampara_1.csv", "town": "Uhana", "district": "Ampara", "pv_capacity_kwp": 20},
#   {"file": "CRN 53616 walahanduwa Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 10},
#   {"file": "CRN 53652 halpotha Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 22.32},
#   {"file": "CRN 53689 Kurudu wattha Akmeemana_1.csv", "town": "Akmeemana", "district": "Galle", "pv_capacity_kwp": 5.58},
#   {"file": "CRN 53751 Mahaladuwa Balapitiya_1.csv", "town": "Balapitiya", "district": "Galle", "pv_capacity_kwp": 14.88},
#   {"file": "CRN 53974 (Weligama).csv", "town": "Weligama", "district": "Matara", "pv_capacity_kwp": 5},
#   {"file": "CRN 8644 Udumulla,Hikkaduwa._1.csv", "town": "Hikkaduwa", "district": "Galle", "pv_capacity_kwp": 5},
#   {"file": "CRN 962 Panvila, Pathana, Hikkaduwa_1.csv", "town": "Hikkaduwa", "district": "Galle", "pv_capacity_kwp": 5},
#   {"file": "CRN.24542.csv", "town": "Kalametiya", "district": "Hambantota", "pv_capacity_kwp": 6.3},
#   {"file": "CRN12243.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 5.1},
#   {"file": "CRN13498 T Bay_1.csv", "town": "Tangalle", "district": "Hambantota", "pv_capacity_kwp": 17.9},
#   {"file": "CRN14037 (Hybrid).csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 6},
#   {"file": "CRN25287.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 1.95},
#   {"file": "CRN31412 South Kalutara.csv", "town": "Kalutara", "district": "Kalutara", "pv_capacity_kwp": 4.96},
#   {"file": "CRN33200- Dr Niroshan.csv", "town": "Kalutara", "district": "Kalutara", "pv_capacity_kwp": 5},
#   {"file": "CRN35216_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 6.12},
#   {"file": "CRN35737 Mullegewaththa Kalahe Wanchawala.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 3.25},
#   {"file": "CRN35857.csv", "town": "Weniyarawela", "district": "Galle", "pv_capacity_kwp": 4.4},
#   {"file": "CRN38340 Nagoda Kaluthra South.csv", "town": "Kalutara", "district": "Kalutara", "pv_capacity_kwp": 5}
# ]

In [19]:
infolist=[
{"file": "CRN 10049 Meepe,Habaraduwa_1.csv", "town": "Habaraduwa", "district": "Galle", "pv_capacity_kwp": 6.48, "latitude": 5.9977, "longitude": 80.2958},
{"file": "CRN 11630 Molligoda,Wadduwa (Convert)_1.csv", "town": "Wadduwa", "district": "Kalutara", "pv_capacity_kwp": 5, "latitude": 6.6640, "longitude": 79.9305}, 
{"file": "CRN 11183 Ambalangoda_1.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 15, "latitude": 6.2353, "longitude": 80.0550},
{"file": "CRN 12157.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 5.2, "latitude": 6.2353, "longitude": 80.0550},
{"file": "CRN 18434 Polwatta Road, Ambalangoda_1.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 5, "latitude": 6.2353, "longitude": 80.0550},
{"file": "CRN 52674 Porabha Ambalangoda_1.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 6, "latitude": 6.2353, "longitude": 80.0550},
{"file": "CRN 52674 Porabha Ambalangoda_2.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 6, "latitude": 6.2353, "longitude": 80.0550},
{"file": "CRN 52919 Wathugedara Ambalangoda_1.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 8, "latitude": 6.2353, "longitude": 80.0550},
{"file": "CRN 38794 Ambalangoda.csv", "town": "Ambalangoda", "district": "Galle", "pv_capacity_kwp": 3.1, "latitude": 6.2353, "longitude": 80.0550},


{"file": "CRN 12200 ( Hybrid )Milidduwa, Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 5, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN 14857 Karapitiya Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 6, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN 31575 Hirimbura Road, Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 3.2, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN 33061_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 8, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN 34350 Walahanduwa,Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 3, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN 37399 Karaputiya.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 3.9, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN 39828 Anagarika dharmapala mawatha Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 6, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN 40400 Labuduwa, Gall_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 5, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN 49244 Bope Cross Rd,Galle._1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 4.95, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN 53616 walahanduwa Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 10, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN 53652 halpotha Galle_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 22.32, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN12243.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 5.1, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN14037 (Hybrid).csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 6, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN25287.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 1.95, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN35216_1.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 6.12, "latitude": 6.0329, "longitude": 80.2168},
{"file": "CRN35737 Mullegewaththa Kalahe Wanchawala.csv", "town": "Galle", "district": "Galle", "pv_capacity_kwp": 3.25, "latitude": 6.0329, "longitude": 80.2168},


{"file": "CRN 18649 Thottawatta Road, Ahungalla_1.csv", "town": "Ahungalla", "district": "Galle", "pv_capacity_kwp": 7.25, "latitude": 6.3117, "longitude": 80.0345},

{"file": "CRN 26198 ( Hybrid ) Weheragoda,Ahangama.csv", "town": "Ahangama", "district": "Galle", "pv_capacity_kwp": 5.5, "latitude": 5.9726, "longitude": 80.3653},
{"file": "CRN 52354_1.csv", "town": "Ahangama", "district": "Galle", "pv_capacity_kwp": 17, "latitude": 5.9726, "longitude": 80.3653},

{"file": "CRN 28970 Handigoda Hikkaduwa_1.csv", "town": "Hikkaduwa", "district": "Galle", "pv_capacity_kwp": 5, "latitude": 6.1396, "longitude": 80.1030},
{"file": "CRN 8644 Udumulla,Hikkaduwa._1.csv", "town": "Hikkaduwa", "district": "Galle", "pv_capacity_kwp": 5, "latitude": 6.1396, "longitude": 80.1030},
{"file": "CRN 962 Panvila, Pathana, Hikkaduwa_1.csv", "town": "Hikkaduwa", "district": "Galle", "pv_capacity_kwp": 5, "latitude": 6.1396, "longitude": 80.1030},

{"file": "CRN 32558 Pitiwella,Boossa_1.csv", "town": "Pitiwella", "district": "Galle", "pv_capacity_kwp": 5, "latitude": 6.0712, "longitude": 80.1691},

{"file": "CRN 39939 Thawaluwila, Ambalantota (Convert)_1.csv", "town": "Ambalantota", "district": "Hambantota", "pv_capacity_kwp": 5, "latitude": 6.1225, "longitude": 81.0239},
{"file": "CRN 40774 Payagala Kaluthara_1.csv", "town": "Payagala", "district": "Kalutara", "pv_capacity_kwp": 20, "latitude": 6.5683, "longitude": 79.9825},
{"file": "CRN 41208 mathugama pradeshiya saba_1.csv", "town": "Matugama", "district": "Kalutara", "pv_capacity_kwp": 6, "latitude": 6.5222, "longitude":  80.1147},
{"file": "CRN 52890 Molligoda Wadduwa_1.csv", "town": "Wadduwa", "district": "Kalutara", "pv_capacity_kwp": 5, "latitude": 6.6640, "longitude": 79.9305},

{"file": "CRN 53084, K K M R I W D K Purijjala, Sella Katharagama_1.csv", "town": "Sella Kataragama", "district": "Monaragala", "pv_capacity_kwp": 27.5, "latitude": 6.4442, "longitude": 81.3090},
{"file": "CRN 53204 Mailagama Katharagama_1.csv", "town": "Sella Kataragama", "district": "Monaragala", "pv_capacity_kwp": 16.52, "latitude": 6.4442, "longitude": 81.3090},

{"file": "CRN 53200 Meegahawela road Beliattha_1.csv", "town": "Beliatta", "district": "Hambantota", "pv_capacity_kwp": 15.4, "latitude": 6.0394, "longitude": 80.7445},
{"file": "CRN 53444 Thissapura Uhana ampara_1.csv", "town": "Uhana", "district": "Ampara", "pv_capacity_kwp": 20, "latitude": 7.3323, "longitude": 81.6781},
{"file": "CRN 53689 Kurudu wattha Akmeemana_1.csv", "town": "Akmeemana", "district": "Galle", "pv_capacity_kwp": 5.58, "latitude": 6.0664, "longitude": 80.2589},
{"file": "CRN 53751 Mahaladuwa Balapitiya_1.csv", "town": "Balapitiya", "district": "Galle", "pv_capacity_kwp": 14.88, "latitude": 6.2731, "longitude": 80.0392},
{"file": "CRN 53974 (Weligama).csv", "town": "Weligama", "district": "Matara", "pv_capacity_kwp": 5, "latitude": 5.9722, "longitude": 80.4287},
{"file": "CRN.24542.csv", "town": "Kalametiya", "district": "Hambantota", "pv_capacity_kwp": 6.3, "latitude": 6.0839, "longitude": 80.9404},
{"file": "CRN13498 T Bay_1.csv", "town": "Tangalle", "district": "Hambantota", "pv_capacity_kwp": 17.9, "latitude": 6.0243, "longitude": 80.7942},

{"file": "CRN31412 South Kalutara.csv", "town": "Kalutara", "district": "Kalutara", "pv_capacity_kwp": 4.96, "latitude": 6.5854, "longitude": 79.9607},
{"file": "CRN33200- Dr Niroshan.csv", "town": "Kalutara", "district": "Kalutara", "pv_capacity_kwp": 5, "latitude": 6.5854, "longitude": 79.9607},
{"file": "CRN38340 Nagoda Kaluthra South.csv", "town": "Kalutara", "district": "Kalutara", "pv_capacity_kwp": 5, "latitude": 6.5854, "longitude": 79.9607},

{"file": "CRN35857.csv", "town": "Weniyarawela", "district": "Galle", "pv_capacity_kwp": 4.4, "latitude": 6.1865, "longitude": 80.1652},
]

1. .bigdata/ folder must contain renamed orignal raw dataset

In [ ]:
from pathlib import Path



chartdata_folder =  Path("data/.bigdata/")

existing_files = {
    path.name.casefold(): path 
    for path in chartdata_folder.rglob("*")
    if path.is_file()
}

found = []
missing = []

for item in infolist:
    filename = item["file"]
    matching_path = existing_files.get(filename.casefold())

    if matching_path:
        found.append((filename, matching_path))
    else:
        missing.append(filename)

print(f"Found: {len(found)}")
print(f"Missing: {len(missing)}")

Found: 49
Missing: 0

### add new data to csv

2. in this code for each file append new data

In [21]:

import pandas as pd

info_by_filename = {
    item["file"].casefold(): item
    for item in infolist
}

updated = []
missing_from_infolist = []
errors = []

for csv_path in chartdata_folder.rglob("*.csv"):
    filename = csv_path.name
    info = info_by_filename.get(filename.casefold())

    if info is None:
        missing_from_infolist.append(filename)
        continue

    try:
        # Read CSV while reducing mixed-type inference warnings
        df = pd.read_csv(csv_path, low_memory=False)

        # Build all metadata columns together
        metadata = pd.DataFrame({
            "file": [filename] * len(df),
            "town": [info["town"]] * len(df),
            "district": [info["district"]] * len(df),
            "pv_capacity_kwp": [info["pv_capacity_kwp"]] * len(df),
            "longitude": [info["longitude"]] * len(df),
            "latitude": [info["latitude"]] * len(df),
        }, index=df.index)

        # Replace existing metadata columns instead of duplicating them
        df = df.drop(
            columns=metadata.columns.intersection(df.columns),
            errors="ignore"
        )

        # Combine the original data and metadata
        df = pd.concat([df, metadata], axis=1)

        # Overwrite the original file
        df.to_csv(csv_path, index=False)

        updated.append(filename)

    except Exception as error:
        errors.append((filename, str(error)))

print(f"Updated: {len(updated)}")
print(f"Missing from infolist: {len(missing_from_infolist)}")
print(f"Errors: {len(errors)}")

print("\nUpdated files:")
print(updated)

print("\nFiles missing from infolist:")
print(missing_from_infolist)

print("\nErrors:")
print(errors)

Updated: 49
Missing from infolist: 0
Errors: 0

Updated files:
['CRN 10049 Meepe,Habaraduwa_1.csv', 'CRN 11183 Ambalangoda_1.csv', 'CRN 11630 Molligoda,Wadduwa (Convert)_1.csv', 'CRN 12157.csv', 'CRN 12200 ( Hybrid )Milidduwa, Galle_1.csv', 'CRN 14857 Karapitiya Galle_1.csv', 'CRN 18434 Polwatta Road, Ambalangoda_1.csv', 'CRN 18649 Thottawatta Road, Ahungalla_1.csv', 'CRN 26198 ( Hybrid ) Weheragoda,Ahangama.csv', 'CRN 28970 Handigoda Hikkaduwa_1.csv', 'CRN 31575 Hirimbura Road, Galle_1.csv', 'CRN 32558 Pitiwella,Boossa_1.csv', 'CRN 33061_1.csv', 'CRN 34350 Walahanduwa,Galle_1.csv', 'CRN 37399 Karaputiya.csv', 'CRN 38794 Ambalangoda.csv', 'CRN 39828 Anagarika dharmapala mawatha Galle_1.csv', 'CRN 39939 Thawaluwila, Ambalantota (Convert)_1.csv', 'CRN 40400 Labuduwa, Gall_1.csv', 'CRN 40774 Payagala Kaluthara_1.csv', 'CRN 41208 mathugama pradeshiya saba_1.csv', 'CRN 49244 Bope Cross Rd,Galle._1.csv', 'CRN 52354_1.csv', 'CRN 52674 Porabha Ambalangoda_1.csv', 'CRN 52674 Porabha Ambalangoda_2.csv', 'CRN 52890 Molligoda Wadduwa_1.csv', 'CRN 52919 Wathugedara Ambalangoda_1.csv', 'CRN 53084, K K M R I W D K Purijjala, Sella Katharagama_1.csv', 'CRN 53200 Meegahawela road Beliattha_1.csv', 'CRN 53204 Mailagama Katharagama_1.csv', 'CRN 53444 Thissapura Uhana ampara_1.csv', 'CRN 53616 walahanduwa Galle_1.csv', 'CRN 53652 halpotha Galle_1.csv', 'CRN 53689 Kurudu wattha Akmeemana_1.csv', 'CRN 53751 Mahaladuwa Balapitiya_1.csv', 'CRN 53974 (Weligama).csv', 'CRN 8644 Udumulla,Hikkaduwa._1.csv', 'CRN 962 Panvila, Pathana, Hikkaduwa_1.csv', 'CRN.24542.csv', 'CRN12243.csv', 'CRN13498 T Bay_1.csv', 'CRN14037 (Hybrid).csv', 'CRN25287.csv', 'CRN31412 South Kalutara.csv', 'CRN33200- Dr Niroshan.csv', 'CRN35216_1.csv', 'CRN35737 Mullegewaththa Kalahe Wanchawala.csv', 'CRN35857.csv', 'CRN38340 Nagoda Kaluthra South.csv']

Files missing from infolist:
[]

Errors:
[]

### remove unimportant data

3. this will update the same files

In [25]:
from pathlib import Path
import pandas as pd

INPUT_FOLDER = Path(
    r"C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\preprocessing\.bigdata"
)

OUTPUT_COLUMNS = [
    "device_number",
    "file",
    "inverterSn",
    "dataTimestamp",
    "timeStr",
    "time",
    "pac",
    "eToday",
    "currentState",
    "warningInfoData",
    "alarmState",
    "productModel",
    "psumCal",
    "pvAndAcCoupledPower",
    "town",
    "district",
    "longitude",
    "latitude",
]

csv_files = sorted(INPUT_FOLDER.glob("*.csv"))

for device_number, csv_file in enumerate(csv_files, start=1):
    print(f"Processing: {csv_file.name}")

    # Read one CSV file
    df = pd.read_csv(csv_file, low_memory=False)

    # Prepare the required columns without repeatedly inserting columns
    data = {
        column: (
            df[column].reset_index(drop=True)
            if column in df.columns
            else pd.Series(pd.NA, index=range(len(df)))
        )
        for column in OUTPUT_COLUMNS
        if column not in ("device_number", "file")
    }

    # Add metadata columns
    data["device_number"] = pd.Series(
        [device_number] * len(df), dtype="int64"
    )
    data["file"] = pd.Series(
        [csv_file.name] * len(df), dtype="object"
    )

    # Build a fresh DataFrame in the required column order
    updated_df = pd.DataFrame(data, columns=OUTPUT_COLUMNS)

    # Overwrite the original CSV file
    updated_df.to_csv(csv_file, index=False)

    print(f"Updated: {csv_file.name} ({len(updated_df):,} rows)")

print(f"\nCompleted. Processed {len(csv_files)} CSV files.")

Processing: CRN 10049 Meepe,Habaraduwa_1.csv
Updated: CRN 10049 Meepe,Habaraduwa_1.csv (486 rows)
Processing: CRN 11183 Ambalangoda_1.csv
Updated: CRN 11183 Ambalangoda_1.csv (129,509 rows)
Processing: CRN 11630 Molligoda,Wadduwa (Convert)_1.csv
Updated: CRN 11630 Molligoda,Wadduwa (Convert)_1.csv (89,191 rows)
Processing: CRN 12157.csv
Updated: CRN 12157.csv (32,635 rows)
Processing: CRN 12200 ( Hybrid )Milidduwa, Galle_1.csv
Updated: CRN 12200 ( Hybrid )Milidduwa, Galle_1.csv (24,380 rows)
Processing: CRN 14857 Karapitiya Galle_1.csv
Updated: CRN 14857 Karapitiya Galle_1.csv (112,402 rows)
Processing: CRN 18434 Polwatta Road, Ambalangoda_1.csv
Updated: CRN 18434 Polwatta Road, Ambalangoda_1.csv (55,262 rows)
Processing: CRN 18649 Thottawatta Road, Ahungalla_1.csv
Updated: CRN 18649 Thottawatta Road, Ahungalla_1.csv (100,671 rows)
Processing: CRN 26198 ( Hybrid ) Weheragoda,Ahangama.csv
Updated: CRN 26198 ( Hybrid ) Weheragoda,Ahangama.csv (25,060 rows)
Processing: CRN 28970 Handigoda Hikkaduwa_1.csv
Updated: CRN 28970 Handigoda Hikkaduwa_1.csv (36,998 rows)
Processing: CRN 31575 Hirimbura Road, Galle_1.csv
Updated: CRN 31575 Hirimbura Road, Galle_1.csv (108,313 rows)
Processing: CRN 32558 Pitiwella,Boossa_1.csv
Updated: CRN 32558 Pitiwella,Boossa_1.csv (81,082 rows)
Processing: CRN 33061_1.csv
Updated: CRN 33061_1.csv (144,476 rows)
Processing: CRN 34350 Walahanduwa,Galle_1.csv
Updated: CRN 34350 Walahanduwa,Galle_1.csv (5,589 rows)
Processing: CRN 37399 Karaputiya.csv
Updated: CRN 37399 Karaputiya.csv (4,859 rows)
Processing: CRN 38794 Ambalangoda.csv
Updated: CRN 38794 Ambalangoda.csv (7,930 rows)
Processing: CRN 39828 Anagarika dharmapala mawatha Galle_1.csv
Updated: CRN 39828 Anagarika dharmapala mawatha Galle_1.csv (151,527 rows)
Processing: CRN 39939 Thawaluwila, Ambalantota (Convert)_1.csv
Updated: CRN 39939 Thawaluwila, Ambalantota (Convert)_1.csv (87,714 rows)
Processing: CRN 40400 Labuduwa, Gall_1.csv
Updated: CRN 40400 Labuduwa, Gall_1.csv (76,879 rows)
Processing: CRN 40774 Payagala Kaluthara_1.csv
Updated: CRN 40774 Payagala Kaluthara_1.csv (133,274 rows)
Processing: CRN 41208 mathugama pradeshiya saba_1.csv
Updated: CRN 41208 mathugama pradeshiya saba_1.csv (44,503 rows)
Processing: CRN 49244 Bope Cross Rd,Galle._1.csv
Updated: CRN 49244 Bope Cross Rd,Galle._1.csv (47,982 rows)
Processing: CRN 52354_1.csv
Updated: CRN 52354_1.csv (254,759 rows)
Processing: CRN 52674 Porabha Ambalangoda_1.csv
Updated: CRN 52674 Porabha Ambalangoda_1.csv (19,365 rows)
Processing: CRN 52674 Porabha Ambalangoda_2.csv
Updated: CRN 52674 Porabha Ambalangoda_2.csv (18,989 rows)
Processing: CRN 52890 Molligoda Wadduwa_1.csv
Updated: CRN 52890 Molligoda Wadduwa_1.csv (125,386 rows)
Processing: CRN 52919 Wathugedara Ambalangoda_1.csv
Updated: CRN 52919 Wathugedara Ambalangoda_1.csv (121,581 rows)
Processing: CRN 53084, K K M R I W D K Purijjala, Sella Katharagama_1.csv
Updated: CRN 53084, K K M R I W D K Purijjala, Sella Katharagama_1.csv (107,126 rows)
Processing: CRN 53200 Meegahawela road Beliattha_1.csv
Updated: CRN 53200 Meegahawela road Beliattha_1.csv (16,316 rows)
Processing: CRN 53204 Mailagama Katharagama_1.csv
Updated: CRN 53204 Mailagama Katharagama_1.csv (16,084 rows)
Processing: CRN 53444 Thissapura Uhana ampara_1.csv
Updated: CRN 53444 Thissapura Uhana ampara_1.csv (67,259 rows)
Processing: CRN 53616 walahanduwa Galle_1.csv
Updated: CRN 53616 walahanduwa Galle_1.csv (67,127 rows)
Processing: CRN 53652 halpotha Galle_1.csv
Updated: CRN 53652 halpotha Galle_1.csv (67,077 rows)
Processing: CRN 53689 Kurudu wattha Akmeemana_1.csv
Updated: CRN 53689 Kurudu wattha Akmeemana_1.csv (43,015 rows)
Processing: CRN 53751 Mahaladuwa Balapitiya_1.csv
Updated: CRN 53751 Mahaladuwa Balapitiya_1.csv (52,625 rows)
Processing: CRN 53974 (Weligama).csv
Updated: CRN 53974 (Weligama).csv (4,742 rows)
Processing: CRN 8644 Udumulla,Hikkaduwa._1.csv
Updated: CRN 8644 Udumulla,Hikkaduwa._1.csv (137,846 rows)
Processing: CRN 962 Panvila, Pathana, Hikkaduwa_1.csv
Updated: CRN 962 Panvila, Pathana, Hikkaduwa_1.csv (70,525 rows)
Processing: CRN.24542.csv
Updated: CRN.24542.csv (16,730 rows)
Processing: CRN12243.csv
Updated: CRN12243.csv (9,475 rows)
Processing: CRN13498 T Bay_1.csv
Updated: CRN13498 T Bay_1.csv (46,303 rows)
Processing: CRN14037 (Hybrid).csv
Updated: CRN14037 (Hybrid).csv (23,283 rows)
Processing: CRN25287.csv
Updated: CRN25287.csv (43,814 rows)
Processing: CRN31412 South Kalutara.csv
Updated: CRN31412 South Kalutara.csv (35,474 rows)
Processing: CRN33200- Dr Niroshan.csv
Updated: CRN33200- Dr Niroshan.csv (8,338 rows)
Processing: CRN35216_1.csv
Updated: CRN35216_1.csv (51,511 rows)
Processing: CRN35737 Mullegewaththa Kalahe Wanchawala.csv
Updated: CRN35737 Mullegewaththa Kalahe Wanchawala.csv (43,629 rows)
Processing: CRN35857.csv
Updated: CRN35857.csv (25,222 rows)
Processing: CRN38340 Nagoda Kaluthra South.csv
Updated: CRN38340 Nagoda Kaluthra South.csv (34,897 rows)

Completed. Processed 49 CSV files.

## Round up the 5 minute time interverls

4. this will create a new folder named aligned_5min

In [3]:
from pathlib import Path
import pandas as pd

INPUT_FOLDER = Path(r"C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data\.bigdata")
OUTPUT_FOLDER = Path(r"C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data") / "aligned_5min_01 preprocessing_solar"

OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

csv_files = sorted(INPUT_FOLDER.glob("*.csv"))

if not csv_files:
    raise FileNotFoundError(f"No CSV files found in {INPUT_FOLDER}")

report = []

for source in csv_files:
    destination = OUTPUT_FOLDER / source.name

    if destination.exists():
        print(f"SKIPPED: {source.name} — output already exists")
        continue

    try:
        # Preserve long inverter identifiers and original field values.
        df = pd.read_csv(
            source,
            dtype="string",
            encoding="utf-8-sig",
        )

        required = {"inverterSn", "dataTimestamp", "time"}
        missing = required - set(df.columns)

        if missing:
            raise ValueError(f"Missing required columns: {sorted(missing)}")

        # Parse the original Unix timestamp without losing milliseconds.
        epoch_ms = pd.to_numeric(df["dataTimestamp"], errors="coerce")

        timestamp_utc = pd.to_datetime(
            epoch_ms,
            unit="ms",
            utc=True,
            errors="coerce",
        )

        timestamp_local = timestamp_utc.dt.tz_convert("Asia/Colombo")

        # `time` is local Sri Lankan time in your sample.
        recorded_local = (
            pd.to_datetime(
                df["time"],
                format="%Y-%m-%d %H:%M:%S",
                errors="coerce",
            )
            .dt.tz_localize("Asia/Colombo")
        )

        df["timestamp_utc"] = timestamp_utc
        df["timestamp_local"] = timestamp_local

        df["timestamp_invalid"] = (
            timestamp_local.isna() | recorded_local.isna()
        )

        # Allow one second because `time` omits milliseconds.
        df["time_difference_seconds"] = (
            timestamp_local - recorded_local
        ).dt.total_seconds()

        df["timestamp_mismatch"] = (
            df["time_difference_seconds"].abs() > 1
        )

        # Round to the nearest five-minute grid point.
        df["timestamp_5min"] = timestamp_local.dt.round("5min")

        df["alignment_shift_seconds"] = (
            df["timestamp_5min"] - timestamp_local
        ).dt.total_seconds()

        # Flag collisions; retain every original row.
        keys = ["inverterSn", "timestamp_5min"]

        valid_key = (
            df["inverterSn"].notna()
            & df["inverterSn"].str.strip().ne("")
            & df["timestamp_5min"].notna()
        )

        df["duplicate_5min"] = False
        df.loc[valid_key, "duplicate_5min"] = (
            df.loc[valid_key].duplicated(keys, keep=False)
        )

        df = df.sort_values(
            ["inverterSn", "timestamp_local"],
            kind="stable",
        )

        df.to_csv(destination, index=False, encoding="utf-8-sig")

        report.append({
            "file": source.name,
            "rows": len(df),
            "invalid_timestamps": int(df["timestamp_invalid"].sum()),
            "timestamp_mismatches": int(df["timestamp_mismatch"].sum()),
            "rows_with_duplicate_5min": int(df["duplicate_5min"].sum()),
        })

        print(f"SAVED: {source.name} — {len(df):,} rows")

    except (ValueError, OSError, pd.errors.ParserError) as error:
        report.append({
            "file": source.name,
            "error": str(error),
        })
        print(f"FAILED: {source.name} — {error}")

if report:
    pd.DataFrame(report).to_csv(
        OUTPUT_FOLDER / "alignment_report.csv",
        index=False,
        encoding="utf-8-sig",
    )

print(f"\nFinished. Output folder: {OUTPUT_FOLDER}")

SAVED: CRN 10049 Meepe,Habaraduwa_1.csv — 486 rows
SAVED: CRN 11183 Ambalangoda_1.csv — 129,509 rows
SAVED: CRN 11630 Molligoda,Wadduwa (Convert)_1.csv — 89,191 rows
SAVED: CRN 12157.csv — 32,635 rows
SAVED: CRN 12200 ( Hybrid )Milidduwa, Galle_1.csv — 24,380 rows
SAVED: CRN 14857 Karapitiya Galle_1.csv — 112,402 rows
SAVED: CRN 18434 Polwatta Road, Ambalangoda_1.csv — 55,262 rows
SAVED: CRN 18649 Thottawatta Road, Ahungalla_1.csv — 100,671 rows
SAVED: CRN 26198 ( Hybrid ) Weheragoda,Ahangama.csv — 25,060 rows
SAVED: CRN 28970 Handigoda Hikkaduwa_1.csv — 36,998 rows
SAVED: CRN 31575 Hirimbura Road, Galle_1.csv — 108,313 rows
SAVED: CRN 32558 Pitiwella,Boossa_1.csv — 81,082 rows
SAVED: CRN 33061_1.csv — 144,476 rows
SAVED: CRN 34350 Walahanduwa,Galle_1.csv — 5,589 rows
SAVED: CRN 37399 Karaputiya.csv — 4,859 rows
SAVED: CRN 38794 Ambalangoda.csv — 7,930 rows
SAVED: CRN 39828 Anagarika dharmapala mawatha Galle_1.csv — 151,527 rows
SAVED: CRN 39939 Thawaluwila, Ambalantota (Convert)_1.csv — 87,714 rows
SAVED: CRN 40400 Labuduwa, Gall_1.csv — 76,879 rows
SAVED: CRN 40774 Payagala Kaluthara_1.csv — 133,274 rows
SAVED: CRN 41208 mathugama pradeshiya saba_1.csv — 44,503 rows
SAVED: CRN 49244 Bope Cross Rd,Galle._1.csv — 47,982 rows
SAVED: CRN 52354_1.csv — 254,759 rows
SAVED: CRN 52674 Porabha Ambalangoda_1.csv — 19,365 rows
SAVED: CRN 52674 Porabha Ambalangoda_2.csv — 18,989 rows
SAVED: CRN 52890 Molligoda Wadduwa_1.csv — 125,386 rows
SAVED: CRN 52919 Wathugedara Ambalangoda_1.csv — 121,581 rows
SAVED: CRN 53084, K K M R I W D K Purijjala, Sella Katharagama_1.csv — 107,126 rows
SAVED: CRN 53200 Meegahawela road Beliattha_1.csv — 16,316 rows
SAVED: CRN 53204 Mailagama Katharagama_1.csv — 16,084 rows
SAVED: CRN 53444 Thissapura Uhana ampara_1.csv — 67,259 rows
SAVED: CRN 53616 walahanduwa Galle_1.csv — 67,127 rows
SAVED: CRN 53652 halpotha Galle_1.csv — 67,077 rows
SAVED: CRN 53689 Kurudu wattha Akmeemana_1.csv — 43,015 rows
SAVED: CRN 53751 Mahaladuwa Balapitiya_1.csv — 52,625 rows
SAVED: CRN 53974 (Weligama).csv — 4,742 rows
SAVED: CRN 8644 Udumulla,Hikkaduwa._1.csv — 137,846 rows
SAVED: CRN 962 Panvila, Pathana, Hikkaduwa_1.csv — 70,525 rows
SAVED: CRN.24542.csv — 16,730 rows
SAVED: CRN12243.csv — 9,475 rows
SAVED: CRN13498 T Bay_1.csv — 46,303 rows
SAVED: CRN14037 (Hybrid).csv — 23,283 rows
SAVED: CRN25287.csv — 43,814 rows
SAVED: CRN31412 South Kalutara.csv — 35,474 rows
SAVED: CRN33200- Dr Niroshan.csv — 8,338 rows
SAVED: CRN35216_1.csv — 51,511 rows
SAVED: CRN35737 Mullegewaththa Kalahe Wanchawala.csv — 43,629 rows
SAVED: CRN35857.csv — 25,222 rows
SAVED: CRN38340 Nagoda Kaluthra South.csv — 34,897 rows

Finished. Output folder: C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data\aligned_5min_01 preprocessing_solar

In [5]:
import pandas as pd

data = pd.read_csv("data/aligned_5min_01 preprocessing_solar/CRN 12157.csv")

In [6]:
data.head()

,device_number,file,inverterSn,dataTimestamp,timeStr,time,pac,eToday,currentState,warningInfoData,...,longitude,latitude,timestamp_utc,timestamp_local,timestamp_invalid,time_difference_seconds,timestamp_mismatch,timestamp_5min,alignment_shift_seconds,duplicate_5min
0,4,CRN 12157.csv,1801150259191341,1766227333061,20/12/2025 16:12:13 (UTC+05:30),2025-12-20 16:12:13,460.0,0.0,正常,0,...,80.055,6.2353,2025-12-20 10:42:13.061000+00:00,2025-12-20 16:12:13.061000+05:30,False,0.061,False,2025-12-20 16:10:00+05:30,-133.061,False
1,4,CRN 12157.csv,1801150259191341,1766227820016,20/12/2025 16:20:20 (UTC+05:30),2025-12-20 16:20:20,300.0,0.0,正常,0,...,80.055,6.2353,2025-12-20 10:50:20.016000+00:00,2025-12-20 16:20:20.016000+05:30,False,0.016,False,2025-12-20 16:20:00+05:30,-20.016,False
2,4,CRN 12157.csv,1801150259191341,1766228120637,20/12/2025 16:25:20 (UTC+05:30),2025-12-20 16:25:20,110.0,0.1,正常,0,...,80.055,6.2353,2025-12-20 10:55:20.637000+00:00,2025-12-20 16:25:20.637000+05:30,False,0.637,False,2025-12-20 16:25:00+05:30,-20.637,False
3,4,CRN 12157.csv,1801150259191341,1766228421268,20/12/2025 16:30:21 (UTC+05:30),2025-12-20 16:30:21,100.0,0.1,正常,0,...,80.055,6.2353,2025-12-20 11:00:21.268000+00:00,2025-12-20 16:30:21.268000+05:30,False,0.268,False,2025-12-20 16:30:00+05:30,-21.268,False
4,4,CRN 12157.csv,1801150259191341,1766228721878,20/12/2025 16:35:21 (UTC+05:30),2025-12-20 16:35:21,120.0,0.1,正常,0,...,80.055,6.2353,2025-12-20 11:05:21.878000+00:00,2025-12-20 16:35:21.878000+05:30,False,0.878,False,2025-12-20 16:35:00+05:30,-21.878,False

## remove rows that alarmState = 2 or 3

this indicate something happend to the inverter reading or fault. so we do not need that

In [7]:
from pathlib import Path
import pandas as pd

INPUT_FOLDER = Path(r"C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data\aligned_5min_01 preprocessing_solar")
OUTPUT_FOLDER = Path(r"C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data") / "filtered_training(no alarmState 2 or 3)_01 preprocessing_solar"

if not INPUT_FOLDER.is_dir():
    raise FileNotFoundError(f"Folder not found: {INPUT_FOLDER}")

OUTPUT_FOLDER.mkdir(exist_ok=True)

for source in sorted(INPUT_FOLDER.glob("*.csv")):
    # Preserve identifiers and original values.
    df = pd.read_csv(source, dtype="string", encoding="utf-8-sig")

    if "alarmState" not in df.columns:
        print(f"SKIPPED: {source.name} — no alarmState column")
        continue

    status = pd.to_numeric(df["alarmState"], errors="coerce")

    # Remove statuses 2 and 3; retain the alarmState column.
    filtered = df.loc[~status.isin([2, 3])].copy()

    filtered.to_csv(
        OUTPUT_FOLDER / source.name,
        index=False,
        encoding="utf-8-sig",
    )

    print(
        f"{source.name}: "
        f"removed {len(df) - len(filtered):,}, "
        f"kept {len(filtered):,}"
    )

print(f"\nSaved to: {OUTPUT_FOLDER}")

SKIPPED: alignment_report.csv — no alarmState column
CRN 10049 Meepe,Habaraduwa_1.csv: removed 71, kept 415
CRN 11183 Ambalangoda_1.csv: removed 4,573, kept 124,936
CRN 11630 Molligoda,Wadduwa (Convert)_1.csv: removed 921, kept 88,270
CRN 12157.csv: removed 380, kept 32,255
CRN 12200 ( Hybrid )Milidduwa, Galle_1.csv: removed 90, kept 24,290
CRN 14857 Karapitiya Galle_1.csv: removed 2,079, kept 110,323
CRN 18434 Polwatta Road, Ambalangoda_1.csv: removed 396, kept 54,866
CRN 18649 Thottawatta Road, Ahungalla_1.csv: removed 1,615, kept 99,056
CRN 26198 ( Hybrid ) Weheragoda,Ahangama.csv: removed 646, kept 24,414
CRN 28970 Handigoda Hikkaduwa_1.csv: removed 13, kept 36,985
CRN 31575 Hirimbura Road, Galle_1.csv: removed 1,471, kept 106,842
CRN 32558 Pitiwella,Boossa_1.csv: removed 173, kept 80,909
CRN 33061_1.csv: removed 485, kept 143,991
CRN 34350 Walahanduwa,Galle_1.csv: removed 6, kept 5,583
CRN 37399 Karaputiya.csv: removed 0, kept 4,859
CRN 38794 Ambalangoda.csv: removed 110, kept 7,820
CRN 39828 Anagarika dharmapala mawatha Galle_1.csv: removed 806, kept 150,721
CRN 39939 Thawaluwila, Ambalantota (Convert)_1.csv: removed 1,088, kept 86,626
CRN 40400 Labuduwa, Gall_1.csv: removed 405, kept 76,474
CRN 40774 Payagala Kaluthara_1.csv: removed 19,133, kept 114,141
CRN 41208 mathugama pradeshiya saba_1.csv: removed 516, kept 43,987
CRN 49244 Bope Cross Rd,Galle._1.csv: removed 59, kept 47,923
CRN 52354_1.csv: removed 17,541, kept 237,218
CRN 52674 Porabha Ambalangoda_1.csv: removed 984, kept 18,381
CRN 52674 Porabha Ambalangoda_2.csv: removed 13, kept 18,976
CRN 52890 Molligoda Wadduwa_1.csv: removed 705, kept 124,681
CRN 52919 Wathugedara Ambalangoda_1.csv: removed 1,360, kept 120,221
CRN 53084, K K M R I W D K Purijjala, Sella Katharagama_1.csv: removed 4,047, kept 103,079
CRN 53200 Meegahawela road Beliattha_1.csv: removed 1,220, kept 15,096
CRN 53204 Mailagama Katharagama_1.csv: removed 1,644, kept 14,440
CRN 53444 Thissapura Uhana ampara_1.csv: removed 298, kept 66,961
CRN 53616 walahanduwa Galle_1.csv: removed 3,208, kept 63,919
CRN 53652 halpotha Galle_1.csv: removed 518, kept 66,559
CRN 53689 Kurudu wattha Akmeemana_1.csv: removed 331, kept 42,684
CRN 53751 Mahaladuwa Balapitiya_1.csv: removed 533, kept 52,092
CRN 53974 (Weligama).csv: removed 21, kept 4,721
CRN 8644 Udumulla,Hikkaduwa._1.csv: removed 7,905, kept 129,941
CRN 962 Panvila, Pathana, Hikkaduwa_1.csv: removed 366, kept 70,159
CRN.24542.csv: removed 266, kept 16,464
CRN12243.csv: removed 883, kept 8,592
CRN13498 T Bay_1.csv: removed 369, kept 45,934
CRN14037 (Hybrid).csv: removed 296, kept 22,987
CRN25287.csv: removed 910, kept 42,904
CRN31412 South Kalutara.csv: removed 11, kept 35,463
CRN33200- Dr Niroshan.csv: removed 26, kept 8,312
CRN35216_1.csv: removed 16, kept 51,495
CRN35737 Mullegewaththa Kalahe Wanchawala.csv: removed 1,401, kept 42,228
CRN35857.csv: removed 147, kept 25,075
CRN38340 Nagoda Kaluthra South.csv: removed 142, kept 34,755

Saved to: C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data\filtered_training(no alarmState 2 or 3)_01 preprocessing_solar

## remove colums timestamp_invalid, timestamp_mismatch, or duplicate_5min is True

In [9]:
from pathlib import Path
import pandas as pd

INPUT_FOLDER = Path(r"C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data\filtered_training(no alarmState 2 or 3)_01 preprocessing_solar")
OUTPUT_FOLDER = Path(r"C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data") / "cleaned1_01 preprocessing_solar"

FLAG_COLUMNS = [
    "timestamp_invalid",
    "timestamp_mismatch",
    "duplicate_5min",
]

DROP_COLUMNS = [
    "timeStr",
    "time",
    "eToday",
    "currentState",
    "warningInfoData",
    "alarmState",
    "pvAndAcCoupledPower",
    "productModel",
    "alignment_shift_seconds",
    "time_difference_seconds",
    *FLAG_COLUMNS,
]

if not INPUT_FOLDER.is_dir():
    raise FileNotFoundError(f"Folder not found: {INPUT_FOLDER}")

OUTPUT_FOLDER.mkdir(exist_ok=True)

for source in sorted(INPUT_FOLDER.glob("*.csv")):
    df = pd.read_csv(source, dtype="string", encoding="utf-8-sig")

    missing_flags = [c for c in FLAG_COLUMNS if c not in df.columns]
    if missing_flags:
        print(f"SKIPPED: {source.name} — missing flags: {missing_flags}")
        continue

    # Accept True/False and 1/0 representations.
    flags = df[FLAG_COLUMNS].apply(
        lambda col: col.str.strip().str.lower()
    )

    # Avoid dropping the flags before unresolved values are checked.
    if not flags.isin(["true", "false", "1", "0"]).all().all():
        print(f"SKIPPED: {source.name} — missing or unrecognized flag values")
        continue

    remove_rows = flags.isin(["true", "1"]).any(axis=1)

    cleaned = (
        df.loc[~remove_rows]
        .drop(columns=DROP_COLUMNS, errors="ignore")
    )

    cleaned.to_csv(
        OUTPUT_FOLDER / source.name,
        index=False,
        encoding="utf-8-sig",
    )

    print(
        f"{source.name}: removed {remove_rows.sum():,} rows; "
        f"kept {len(cleaned):,} rows and {len(cleaned.columns)} columns"
    )

print(f"\nSaved to: {OUTPUT_FOLDER}")

CRN 10049 Meepe,Habaraduwa_1.csv: removed 0 rows; kept 415 rows and 13 columns
CRN 11183 Ambalangoda_1.csv: removed 224 rows; kept 124,712 rows and 13 columns
CRN 11630 Molligoda,Wadduwa (Convert)_1.csv: removed 41 rows; kept 88,229 rows and 13 columns
CRN 12157.csv: removed 8 rows; kept 32,247 rows and 13 columns
CRN 12200 ( Hybrid )Milidduwa, Galle_1.csv: removed 113 rows; kept 24,177 rows and 13 columns
CRN 14857 Karapitiya Galle_1.csv: removed 819 rows; kept 109,504 rows and 13 columns
CRN 18434 Polwatta Road, Ambalangoda_1.csv: removed 232 rows; kept 54,634 rows and 13 columns
CRN 18649 Thottawatta Road, Ahungalla_1.csv: removed 110 rows; kept 98,946 rows and 13 columns
CRN 26198 ( Hybrid ) Weheragoda,Ahangama.csv: removed 70 rows; kept 24,344 rows and 13 columns
CRN 28970 Handigoda Hikkaduwa_1.csv: removed 44 rows; kept 36,941 rows and 13 columns
CRN 31575 Hirimbura Road, Galle_1.csv: removed 302 rows; kept 106,540 rows and 13 columns
CRN 32558 Pitiwella,Boossa_1.csv: removed 185 rows; kept 80,724 rows and 13 columns
CRN 33061_1.csv: removed 293 rows; kept 143,698 rows and 13 columns
CRN 34350 Walahanduwa,Galle_1.csv: removed 12 rows; kept 5,571 rows and 13 columns
CRN 37399 Karaputiya.csv: removed 2 rows; kept 4,857 rows and 13 columns
CRN 38794 Ambalangoda.csv: removed 8 rows; kept 7,812 rows and 13 columns
CRN 39828 Anagarika dharmapala mawatha Galle_1.csv: removed 639 rows; kept 150,082 rows and 13 columns
CRN 39939 Thawaluwila, Ambalantota (Convert)_1.csv: removed 271 rows; kept 86,355 rows and 13 columns
CRN 40400 Labuduwa, Gall_1.csv: removed 109 rows; kept 76,365 rows and 13 columns
CRN 40774 Payagala Kaluthara_1.csv: removed 1,411 rows; kept 112,730 rows and 13 columns
CRN 41208 mathugama pradeshiya saba_1.csv: removed 31 rows; kept 43,956 rows and 13 columns
CRN 49244 Bope Cross Rd,Galle._1.csv: removed 1,112 rows; kept 46,811 rows and 13 columns
CRN 52354_1.csv: removed 3,369 rows; kept 233,849 rows and 13 columns
CRN 52674 Porabha Ambalangoda_1.csv: removed 8 rows; kept 18,373 rows and 13 columns
CRN 52674 Porabha Ambalangoda_2.csv: removed 36 rows; kept 18,940 rows and 13 columns
CRN 52890 Molligoda Wadduwa_1.csv: removed 521 rows; kept 124,160 rows and 13 columns
CRN 52919 Wathugedara Ambalangoda_1.csv: removed 903 rows; kept 119,318 rows and 13 columns
CRN 53084, K K M R I W D K Purijjala, Sella Katharagama_1.csv: removed 196 rows; kept 102,883 rows and 13 columns
CRN 53200 Meegahawela road Beliattha_1.csv: removed 8 rows; kept 15,088 rows and 13 columns
CRN 53204 Mailagama Katharagama_1.csv: removed 35 rows; kept 14,405 rows and 13 columns
CRN 53444 Thissapura Uhana ampara_1.csv: removed 434 rows; kept 66,527 rows and 13 columns
CRN 53616 walahanduwa Galle_1.csv: removed 180 rows; kept 63,739 rows and 13 columns
CRN 53652 halpotha Galle_1.csv: removed 30 rows; kept 66,529 rows and 13 columns
CRN 53689 Kurudu wattha Akmeemana_1.csv: removed 126 rows; kept 42,558 rows and 13 columns
CRN 53751 Mahaladuwa Balapitiya_1.csv: removed 88 rows; kept 52,004 rows and 13 columns
CRN 53974 (Weligama).csv: removed 80 rows; kept 4,641 rows and 13 columns
CRN 8644 Udumulla,Hikkaduwa._1.csv: removed 235 rows; kept 129,706 rows and 13 columns
CRN 962 Panvila, Pathana, Hikkaduwa_1.csv: removed 54 rows; kept 70,105 rows and 13 columns
CRN.24542.csv: removed 6 rows; kept 16,458 rows and 13 columns
CRN12243.csv: removed 52 rows; kept 8,540 rows and 13 columns
CRN13498 T Bay_1.csv: removed 236 rows; kept 45,698 rows and 13 columns
CRN14037 (Hybrid).csv: removed 129 rows; kept 22,858 rows and 13 columns
CRN25287.csv: removed 144 rows; kept 42,760 rows and 13 columns
CRN31412 South Kalutara.csv: removed 18 rows; kept 35,445 rows and 13 columns
CRN33200- Dr Niroshan.csv: removed 70 rows; kept 8,242 rows and 13 columns
CRN35216_1.csv: removed 82 rows; kept 51,413 rows and 13 columns
CRN35737 Mullegewaththa Kalahe Wanchawala.csv: removed 59 rows; kept 42,169 rows and 13 columns
CRN35857.csv: removed 6 rows; kept 25,069 rows and 13 columns
CRN38340 Nagoda Kaluthra South.csv: removed 12 rows; kept 34,743 rows and 13 columns

Saved to: C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data\cleaned1_01 preprocessing_solar

## remove all other rows that does not belong to 06:00:00+05:30 - 19:00:00+05:30 range

In [10]:
from pathlib import Path
import pandas as pd

INPUT_FOLDER = Path(r"C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data\cleaned1_01 preprocessing_solar")
OUTPUT_FOLDER = Path(r"C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data") / "daytime_0600_1900_01 preprocessing_solar"

if not INPUT_FOLDER.is_dir():
    raise FileNotFoundError(f"Folder not found: {INPUT_FOLDER}")

OUTPUT_FOLDER.mkdir(exist_ok=True)

for source in sorted(INPUT_FOLDER.glob("*.csv")):
    df = pd.read_csv(source, dtype="string", encoding="utf-8-sig")

    if "timestamp_5min" not in df.columns:
        print(f"SKIPPED: {source.name} — missing timestamp_5min")
        continue

    # Aligned timestamps already contain their timezone offset.
    local_time = pd.to_datetime(
        df["timestamp_5min"],
        utc=True,
        errors="coerce",
    ).dt.tz_convert("Asia/Colombo")

    seconds = (
        local_time.dt.hour * 3600
        + local_time.dt.minute * 60
        + local_time.dt.second
    )

    keep = seconds.between(6 * 3600, 19 * 3600, inclusive="both")
    filtered = df.loc[keep].copy()

    filtered.to_csv(
        OUTPUT_FOLDER / source.name,
        index=False,
        encoding="utf-8-sig",
    )

    print(
        f"{source.name}: kept {len(filtered):,}; "
        f"removed {len(df) - len(filtered):,}; "
        f"invalid timestamps {local_time.isna().sum():,}"
    )

print(f"\nSaved to: {OUTPUT_FOLDER}")

CRN 10049 Meepe,Habaraduwa_1.csv: kept 415; removed 0; invalid timestamps 0
CRN 11183 Ambalangoda_1.csv: kept 124,569; removed 143; invalid timestamps 0
CRN 11630 Molligoda,Wadduwa (Convert)_1.csv: kept 88,184; removed 45; invalid timestamps 0
CRN 12157.csv: kept 32,244; removed 3; invalid timestamps 0
CRN 12200 ( Hybrid )Milidduwa, Galle_1.csv: kept 13,104; removed 11,073; invalid timestamps 0
CRN 14857 Karapitiya Galle_1.csv: kept 109,470; removed 34; invalid timestamps 0
CRN 18434 Polwatta Road, Ambalangoda_1.csv: kept 54,634; removed 0; invalid timestamps 0
CRN 18649 Thottawatta Road, Ahungalla_1.csv: kept 98,931; removed 15; invalid timestamps 0
CRN 26198 ( Hybrid ) Weheragoda,Ahangama.csv: kept 13,008; removed 11,336; invalid timestamps 0
CRN 28970 Handigoda Hikkaduwa_1.csv: kept 36,941; removed 0; invalid timestamps 0
CRN 31575 Hirimbura Road, Galle_1.csv: kept 106,384; removed 156; invalid timestamps 0
CRN 32558 Pitiwella,Boossa_1.csv: kept 57,564; removed 23,160; invalid timestamps 0
CRN 33061_1.csv: kept 143,617; removed 81; invalid timestamps 0
CRN 34350 Walahanduwa,Galle_1.csv: kept 5,571; removed 0; invalid timestamps 0
CRN 37399 Karaputiya.csv: kept 4,847; removed 10; invalid timestamps 0
CRN 38794 Ambalangoda.csv: kept 7,801; removed 11; invalid timestamps 0
CRN 39828 Anagarika dharmapala mawatha Galle_1.csv: kept 148,861; removed 1,221; invalid timestamps 0
CRN 39939 Thawaluwila, Ambalantota (Convert)_1.csv: kept 86,320; removed 35; invalid timestamps 0
CRN 40400 Labuduwa, Gall_1.csv: kept 76,349; removed 16; invalid timestamps 0
CRN 40774 Payagala Kaluthara_1.csv: kept 112,609; removed 121; invalid timestamps 0
CRN 41208 mathugama pradeshiya saba_1.csv: kept 43,928; removed 28; invalid timestamps 0
CRN 49244 Bope Cross Rd,Galle._1.csv: kept 46,810; removed 1; invalid timestamps 0
CRN 52354_1.csv: kept 137,652; removed 96,197; invalid timestamps 0
CRN 52674 Porabha Ambalangoda_1.csv: kept 18,330; removed 43; invalid timestamps 0
CRN 52674 Porabha Ambalangoda_2.csv: kept 18,936; removed 4; invalid timestamps 0
CRN 52890 Molligoda Wadduwa_1.csv: kept 124,143; removed 17; invalid timestamps 0
CRN 52919 Wathugedara Ambalangoda_1.csv: kept 119,300; removed 18; invalid timestamps 0
CRN 53084, K K M R I W D K Purijjala, Sella Katharagama_1.csv: kept 102,200; removed 683; invalid timestamps 0
CRN 53200 Meegahawela road Beliattha_1.csv: kept 15,079; removed 9; invalid timestamps 0
CRN 53204 Mailagama Katharagama_1.csv: kept 14,393; removed 12; invalid timestamps 0
CRN 53444 Thissapura Uhana ampara_1.csv: kept 65,858; removed 669; invalid timestamps 0
CRN 53616 walahanduwa Galle_1.csv: kept 63,679; removed 60; invalid timestamps 0
CRN 53652 halpotha Galle_1.csv: kept 66,304; removed 225; invalid timestamps 0
CRN 53689 Kurudu wattha Akmeemana_1.csv: kept 42,554; removed 4; invalid timestamps 0
CRN 53751 Mahaladuwa Balapitiya_1.csv: kept 51,938; removed 66; invalid timestamps 0
CRN 53974 (Weligama).csv: kept 2,575; removed 2,066; invalid timestamps 0
CRN 8644 Udumulla,Hikkaduwa._1.csv: kept 129,699; removed 7; invalid timestamps 0
CRN 962 Panvila, Pathana, Hikkaduwa_1.csv: kept 70,102; removed 3; invalid timestamps 0
CRN.24542.csv: kept 16,458; removed 0; invalid timestamps 0
CRN12243.csv: kept 4,610; removed 3,930; invalid timestamps 0
CRN13498 T Bay_1.csv: kept 45,537; removed 161; invalid timestamps 0
CRN14037 (Hybrid).csv: kept 12,302; removed 10,556; invalid timestamps 0
CRN25287.csv: kept 42,760; removed 0; invalid timestamps 0
CRN31412 South Kalutara.csv: kept 35,437; removed 8; invalid timestamps 0
CRN33200- Dr Niroshan.csv: kept 4,467; removed 3,775; invalid timestamps 0
CRN35216_1.csv: kept 51,379; removed 34; invalid timestamps 0
CRN35737 Mullegewaththa Kalahe Wanchawala.csv: kept 42,169; removed 0; invalid timestamps 0
CRN35857.csv: kept 24,338; removed 731; invalid timestamps 0
CRN38340 Nagoda Kaluthra South.csv: kept 34,722; removed 21; invalid timestamps 0

Saved to: C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data\daytime_0600_1900_01 preprocessing_solar

## combine data into one file

In [11]:
from pathlib import Path
import pandas as pd

INPUT_FOLDER = Path(r"C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data\daytime_0600_1900_01 preprocessing_solar")
OUTPUT_FILE = Path(r"C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data") / "final_solaronly_combined_01 preprocessing_solar.csv"

# Exclude the output so rerunning cannot combine it with itself.
files = sorted(
    path for path in INPUT_FOLDER.glob("*.csv")
    if path.name.lower() != OUTPUT_FILE.name.lower()
)

if not files:
    raise FileNotFoundError(f"No input CSV files found in {INPUT_FOLDER}")

# Check that every file has the same columns before writing.
columns = pd.read_csv(
    files[0], nrows=0, encoding="utf-8-sig"
).columns.tolist()

for path in files:
    header = pd.read_csv(
        path, nrows=0, encoding="utf-8-sig"
    ).columns.tolist()

    if set(header) != set(columns):
        raise ValueError(f"Columns do not match: {path.name}")

temporary = OUTPUT_FILE.with_suffix(".csv.tmp")
total_rows = 0

try:
    with temporary.open("w", encoding="utf-8-sig", newline="") as output:
        # Write the header once, including when inputs have no rows.
        pd.DataFrame(columns=columns).to_csv(output, index=False)

        for path in files:
            file_rows = 0

            with pd.read_csv(
                path,
                dtype="string",
                encoding="utf-8-sig",
                chunksize=50_000,
            ) as reader:
                for chunk in reader:
                    chunk[columns].to_csv(
                        output, index=False, header=False
                    )
                    file_rows += len(chunk)

            total_rows += file_rows
            print(f"Added: {path.name} — {file_rows:,} rows")

    temporary.replace(OUTPUT_FILE)

finally:
    if temporary.exists():
        temporary.unlink()

print(f"\nCombined {len(files)} files: {total_rows:,} rows")
print(f"Saved to: {OUTPUT_FILE}")

Added: CRN 10049 Meepe,Habaraduwa_1.csv — 415 rows
Added: CRN 11183 Ambalangoda_1.csv — 124,569 rows
Added: CRN 11630 Molligoda,Wadduwa (Convert)_1.csv — 88,184 rows
Added: CRN 12157.csv — 32,244 rows
Added: CRN 12200 ( Hybrid )Milidduwa, Galle_1.csv — 13,104 rows
Added: CRN 14857 Karapitiya Galle_1.csv — 109,470 rows
Added: CRN 18434 Polwatta Road, Ambalangoda_1.csv — 54,634 rows
Added: CRN 18649 Thottawatta Road, Ahungalla_1.csv — 98,931 rows
Added: CRN 26198 ( Hybrid ) Weheragoda,Ahangama.csv — 13,008 rows
Added: CRN 28970 Handigoda Hikkaduwa_1.csv — 36,941 rows
Added: CRN 31575 Hirimbura Road, Galle_1.csv — 106,384 rows
Added: CRN 32558 Pitiwella,Boossa_1.csv — 57,564 rows
Added: CRN 33061_1.csv — 143,617 rows
Added: CRN 34350 Walahanduwa,Galle_1.csv — 5,571 rows
Added: CRN 37399 Karaputiya.csv — 4,847 rows
Added: CRN 38794 Ambalangoda.csv — 7,801 rows
Added: CRN 39828 Anagarika dharmapala mawatha Galle_1.csv — 148,861 rows
Added: CRN 39939 Thawaluwila, Ambalantota (Convert)_1.csv — 86,320 rows
Added: CRN 40400 Labuduwa, Gall_1.csv — 76,349 rows
Added: CRN 40774 Payagala Kaluthara_1.csv — 112,609 rows
Added: CRN 41208 mathugama pradeshiya saba_1.csv — 43,928 rows
Added: CRN 49244 Bope Cross Rd,Galle._1.csv — 46,810 rows
Added: CRN 52354_1.csv — 137,652 rows
Added: CRN 52674 Porabha Ambalangoda_1.csv — 18,330 rows
Added: CRN 52674 Porabha Ambalangoda_2.csv — 18,936 rows
Added: CRN 52890 Molligoda Wadduwa_1.csv — 124,143 rows
Added: CRN 52919 Wathugedara Ambalangoda_1.csv — 119,300 rows
Added: CRN 53084, K K M R I W D K Purijjala, Sella Katharagama_1.csv — 102,200 rows
Added: CRN 53200 Meegahawela road Beliattha_1.csv — 15,079 rows
Added: CRN 53204 Mailagama Katharagama_1.csv — 14,393 rows
Added: CRN 53444 Thissapura Uhana ampara_1.csv — 65,858 rows
Added: CRN 53616 walahanduwa Galle_1.csv — 63,679 rows
Added: CRN 53652 halpotha Galle_1.csv — 66,304 rows
Added: CRN 53689 Kurudu wattha Akmeemana_1.csv — 42,554 rows
Added: CRN 53751 Mahaladuwa Balapitiya_1.csv — 51,938 rows
Added: CRN 53974 (Weligama).csv — 2,575 rows
Added: CRN 8644 Udumulla,Hikkaduwa._1.csv — 129,699 rows
Added: CRN 962 Panvila, Pathana, Hikkaduwa_1.csv — 70,102 rows
Added: CRN.24542.csv — 16,458 rows
Added: CRN12243.csv — 4,610 rows
Added: CRN13498 T Bay_1.csv — 45,537 rows
Added: CRN14037 (Hybrid).csv — 12,302 rows
Added: CRN25287.csv — 42,760 rows
Added: CRN31412 South Kalutara.csv — 35,437 rows
Added: CRN33200- Dr Niroshan.csv — 4,467 rows
Added: CRN35216_1.csv — 51,379 rows
Added: CRN35737 Mullegewaththa Kalahe Wanchawala.csv — 42,169 rows
Added: CRN35857.csv — 24,338 rows
Added: CRN38340 Nagoda Kaluthra South.csv — 34,722 rows

Combined 49 files: 2,769,082 rows
Saved to: C:\Users\pkmpp\Documents\GitHub\J26-DS-323\experiments\pasan\step by step\data\final_solaronly_combined_01 preprocessing_solar.csv